# Generated by Django 2.1.2 on 2018-10-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DjApp.DJ')),
            ],
        ),
        migrations.CreateModel(
            name='SongsInElections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjApp.Elections')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='dj',
        ),
        migrations.AddField(
            model_name='song',
            name='dj',
            field=models.ManyToManyField(to='DjApp.DJ'),
        ),
        migrations.AddField(
            model_name='songsinelections',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjApp.Song'),
        ),
    ]
