# Generated by Django 2.1.2 on 2018-10-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp', '0002_auto_20181013_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='dj',
        ),
        migrations.AddField(
            model_name='song',
            name='dj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DjApp.DJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songsinelections',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjApp.Song'),
        ),
    ]
